import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Lora, Roboto, Open_Sans, JetBrains_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const jeonSoMin = localFont({
  src: "../public/fonts/jeonsomin.ttf",
  variable: "--font-jeonsomin",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NEXT NOTEPAD",
  description: "Generated by bloodstrawberry",
};

import { Toaster } from "@/app/components/toast";
import { SecurePromptProvider } from "@/app/components/secure-prompt";
import { TabGuard } from "@/app/components/tab-guard";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${lora.variable} ${roboto.variable} ${openSans.variable} ${jetbrainsMono.variable} ${jeonSoMin.variable} h-full antialiased`}
    >
      <head>
        <link rel="stylesheet" as="style" crossOrigin="anonymous" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster />
        <SecurePromptProvider />
        <TabGuard />
      </body>
    </html>
  );
}
